# Generated by Django 3.2.9 on 2022-10-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_alter_identity_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'eid',
            },
        ),
        migrations.AlterModelOptions(
            name='identity',
            options={'verbose_name_plural': 'eid'},
        ),
    ]
