# Generated by Django 3.2.9 on 2022-10-15 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20221015_1114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='identity',
        ),
        migrations.AlterModelOptions(
            name='eid',
            options={'verbose_name_plural': 'Eid'},
        ),
    ]
