# Generated by Django 3.2.9 on 2022-10-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20221015_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=200, unique=True)),
                ('mobile_number', models.CharField(max_length=200, unique=True)),
                ('work_institution', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('county', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Personal Profiles',
            },
        ),
    ]
