# Generated by Django 3.2.9 on 2022-10-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_identity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eid',
            options={'verbose_name_plural': 'Electronic Identities'},
        ),
    ]
