# Generated by Django 4.1.5 on 2023-02-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_alter_eid_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='county',
            field=models.CharField(max_length=200),
        ),
    ]
