# Generated by Django 4.1.5 on 2023-02-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_alter_identity_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='constituency',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='identity',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='identity',
            name='ward',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='identity',
            name='county',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
